name: Reveal Secret
on: workflow_dispatch # 手动触发

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Read Secret
        run: |
          # 将 Secret 转成 Base64 避开 GitHub 的自动脱敏过滤
          echo "${{ secrets.COURSE_IDS }}" | base64
